name: Configuration Synchronizer
type: module
description: 'Synchronize your site with updated configuration provided by modules and themes.'
package: Core
version: VERSION
core: 8.x
dependencies:
 - config_update
 